# ********RoostGPT********

# Test generated by RoostGPT for test Test-5619 using AI Type  and AI Model 
# 
# Feature file generated for /order-service/orders/create-profile-account_post for http method type POST 
# RoostTestHash=44a4fe3677
# 
# 

# ********RoostGPT********
Feature: Order Service API testing

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { 'Content-Type': 'application/json', 'Authorization': '#(authToken)', 'channel': '#(channel)', 'X-Trace-Id': '#(xTraceId)', 'userid': '#(userId)', 'username': '#(username)', 'entityId': '#(entityId)' }

  Scenario Outline: Validating the creation of profile account
    Given path '/order-service/orders/create-profile-account'
    When method post
    Then status <statusCode>
    And match response == <responseBody>

    Examples:
      | read('order-service_orders_create-profile-account_post.csv') |
