# ********RoostGPT********

# Test generated by RoostGPT for test Test-5619 using AI Type  and AI Model 
# 
# Feature file generated for /forms/{form-type}/{form-instance-id}_post for http method type POST 
# RoostTestHash=92502ea186
# 
# 

# ********RoostGPT********
Feature: Testing /forms/{form-type}/{form-instance-id} endpoint

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { 'Authorization': '#(authToken)', 'X-HSBC-Request-Correlation-Id': '#(java.util.UUID.randomUUID().toString())' }

  Scenario Outline: Testing valid POST request
    Given path '/forms', '<form-type>', '<form-instance-id>'
    And request { 'form-instance-id': '<form-instance-id>', 'type': '<form-type>', 'status': '<status>', 'currentViewId': '<currentViewId>', 'nextViewId': '<nextViewId>', 'links': '<links>', 'parentId': '<parentId>' }
    When method post
    Then status 200
    And match $ == { 'status': '#string', 'messages': '#object', 'currentViewId': '#string', 'nextViewId': '#string', 'domainSessionId': '#string', 'views': '#array', 'count': '#number', 'cause': '#object' }

    Examples:
      | read('forms_form-type_form-instance-id_post.csv') |

  Scenario Outline: Testing invalid POST request
    Given path '/forms', '<form-type>', '<form-instance-id>'
    And request { 'form-instance-id': '<form-instance-id>', 'type': '<form-type>', 'status': '<status>', 'currentViewId': '<currentViewId>', 'nextViewId': '<nextViewId>', 'links': '<links>', 'parentId': '<parentId>' }
    When method post
    Then status 400
    And match $ == { 'type': '#string', 'title': '#string', 'status': '#string', 'detail': '#string', 'errors': '#array', 'instance': '#string', 'errorDateTime': '#string' }

    Examples:
      | form-type | form-instance-id | status | currentViewId | nextViewId | links | parentId  |
      | 'type3'   | 'instance3'      | '400'  | 'view5'       | 'view6'    | {}    | 'parent3' |
      | 'type4'   | 'instance4'      | '400'  | 'view7'       | 'view8'    | {}    | 'parent4' |

  Scenario: Testing server error
    Given path '/forms', 'type5', 'instance5'
    And request { 'form-instance-id': 'instance5', 'type': 'type5', 'status': '500', 'currentViewId': 'view9', 'nextViewId': 'view10', 'links': {}, 'parentId': 'parent5' }
    When method post
    Then status 500
    And match $ == { 'type': '#string', 'title': '#string', 'status': '#string', 'detail': '#string', 'errors': '#array', 'instance': '#string', 'errorDateTime': '#string' }
