# ********RoostGPT********

# Test generated by RoostGPT for test artillery-test using AI Type  and AI Model 
# 
# Feature file generated for /employees_get for http method type GET 
# RoostTestHash=ec231a756b
# 
# 

# ********RoostGPT********
Feature: Employees API

  Background:
    * def urlBase = karate.properties['jcbkjqcvkjqc_URL_BASE'] || 'http://localhost:4010'
    * url urlBase
    * def auth_token = karate.properties['jcbkjqcvkjqc_AUTH_TOKEN'] ? karate.properties['jcbkjqcvkjqc_AUTH_TOKEN'] : 'default_token'
    * configure headers = { Authorization: '#(auth_token)' }

  Scenario Outline: Search Employees
    Given path '/employees'
    And param searchString = '<searchString>'
    When method get
    Then status 200
    And match $ == '#array'
    And match each $[*] contains { email: '#string', jobTitle: '#string', name: '#string' }

    Examples:
      | read('employees_get.csv') |

  Scenario: Search Employees - Bad Input
    Given path '/employees'
    And param searchString = '123'
    When method get
    Then status 400
