# ********RoostGPT********

# Test generated by RoostGPT for test testing-karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /employees_get for http method type GET 
# RoostTestHash=ec231a756b
# 
# 

# ********RoostGPT********
Feature: Search Employees API

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * header Accept = 'application/json'

  Scenario: Validate Search Employees API with no query parameters
    Given path 'employees'
    When method GET
    Then status 200
    And match response == '#[]'
    And match response[*].id == '#string'
    And match response[*].jobTitle == '#string'
    And match response[*].name == '#string'
    And match response[*].email == '#string'

  Scenario Outline: Validate Search Employees API with search string query parameter
    Given path 'employees'
    And param searchString = <searchString>
    When method GET
    Then status <status>
    And match response == '#[]'
    And match response[*].id == '#string'
    And match response[*].jobTitle == '#string'
    And match response[*].name == '#string'
    And match response[*].email == '#string'

    Examples:
      | searchString     | status |
      | 'System Analyst' |    200 |
      | 'John Smith'     |    200 |
      | ''               |    200 |

  Scenario: Validate Search Employees API with invalid query parameter
    Given path 'employees'
    And param searchString = '!'
    When method GET
    Then status 400
    And match responseStatus != 200
