# ********RoostGPT********

# Test generated by RoostGPT for test test-roostapispec-1 using AI Type  and AI Model 
# 
# Feature file generated for /test_post for http method type POST 
# RoostTestHash=99bb15b7c8
# 
# 

# ********RoostGPT********
Feature: Test API for creating a new application

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * header Authorization = 'Bearer ' + authToken

  Scenario Outline: Create a new application with various configurations
    Given path '/test'
    And request
      """
      {
        "app_id": "<app_id>",
        "test_name": "<test_name>",
        "trigger_events": <trigger_events>,
        "git_ops": <git_ops>,
        "git_type": "<git_type>",
        "ai_model_info": <ai_model_info>,
        "git_info": <git_info>,
        "integration_info": <integration_info>,
        "additional_info": <additional_info>,
        "test_timeout": <test_timeout>,
        "test_framework": "<test_framework>",
        "source_branch": "<source_branch>"
      }
      """
    When method POST
    Then status 201
    And match response ==
      """
      {
        "id": "#string",
        "user_id": "#string",
        "thirdparty_app_id": "#string",
        "test_name": "#string",
        "git_info": "#string",
        "ai_model_info": "#string",
        "integration_info": "#string",
        "additional_info": "#string",
        "trigger_events": "#string",
        "created_on": "#datetime",
        "updated_on": "#datetime",
        "deleted": "#number",
        "test_timeout": "#number",
        "webhook_error": "#string",
        "test_framework": "#string",
        "git_type": "#string",
        "source_repo": "#string",
        "source_branch": "#string",
        "connector_ids": "#string",
        "git_ops": "#number",
        "labels": "#string",
        "test_source": "#? _ == 'jira_plugin'"
      }
      """

    Examples:
      | read('test_post.csv') |
