# ********RoostGPT********

# Test generated by RoostGPT for test test-roostapispec-1 using AI Type Claude AI and AI Model claude-3-5-sonnet-20240620
# 
# Feature file generated for /test/{test_id}/trigger_post for http method type POST 
# RoostTestHash=bce43bf0f9
# 
# 

# ********RoostGPT********
Feature: Test Trigger API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

  Scenario Outline: Trigger Test with valid test_id
    Given path '/test', '<test_id>', 'trigger'
    And header Authorization = 'Bearer ' + authToken
    When method POST
    Then status 201

    Examples:
      | read('test_test_id_trigger_post.csv') |

  Scenario: Trigger Test with invalid test_id
    Given path '/test', 'invalid_id', 'trigger'
    And header Authorization = 'Bearer ' + authToken
    When method POST
    Then status 404
    And match response ==
      """
      {
        code: '#number',
        timestamp: '#string',
        path: '#string',
        method: '#string',
        message: '#string'
      }
      """
    And match response.code == 404
    And match response.path contains '/test/invalid_id/trigger'
    And match response.method == 'POST'
    And match response.message == 'Not found'

  Scenario: Trigger Test without authorization
    Given path '/test', 'test123', 'trigger'
    When method POST
    Then status 401

  Scenario: Trigger Test with invalid HTTP method
    Given path '/test', 'test123', 'trigger'
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 405
