# ********RoostGPT********

# Test generated by RoostGPT for test test-roostapispec-1 using AI Type  and AI Model 
# 
# Feature file generated for /test/{test_id}_delete for http method type DELETE 
# RoostTestHash=78e3edd85a
# 
# 

# ********RoostGPT********
Feature: Delete Test API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

  Scenario Outline: Delete a test with valid test_id
    Given path '/test', '<test_id>'
    And header Authorization = 'Bearer ' + authToken
    When method DELETE
    Then status 200

    Examples:
      | read('test_test_id_delete.csv') |

  Scenario Outline: Delete a test with invalid test_id
    Given path '/test', '<test_id>'
    And header Authorization = 'Bearer ' + authToken
    When method DELETE
    Then status 404
    And match response ==
      """
      {
        code: '#number',
        timestamp: '#string',
        path: '#string',
        method: '#regex ^GET|DELETE|HEAD|OPTIONS|POST|PUT|PATCH|PURGE|LINK|UNLINK$',
        message: '#string'
      }
      """
    And match response.code == 404
    And match response.path contains '/test/'
    And match response.method == 'DELETE'
    And match response.message == 'Not found'

    Examples:
      | test_id   |
      | invalid1  |
      | notfound2 |

  Scenario: Delete a test without authorization
    Given path '/test/test123'
    When method DELETE
    Then status 401
