# ********RoostGPT********

# Test generated by RoostGPT for test test-roostapispec-1 using AI Type Claude AI and AI Model claude-3-5-sonnet-20240620
# 
# Feature file generated for /test/event/{trigger_id}/execute/report_get for http method type GET 
# RoostTestHash=25919140f7
# 
# 

# ********RoostGPT********
Feature: Test Execution Report API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

  Scenario Outline: Test execution report for different file choices and paths
    Given path '/test/event', '<trigger_id>', 'execute/report'
    And param file_choice = '<file_choice>'
    And param file_path = '<file_path>'
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 200
    And match response == '#object'

    Examples:
      | read('test_event_trigger_id_execute_report_get.csv') |

  Scenario: Test execution report with invalid trigger_id
    Given path '/test/event', 'invalid_trigger', 'execute/report'
    And param file_choice = 'choice1'
    And param file_path = '/path/to/file'
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 404
    And match response ==
      """
      {
        code: 404,
        timestamp: '#string',
        path: '/application/client/git/eaas/trigger',
        method: '#enum',
        message: 'Not found'
      }
      """
    And match response.method == '#? _ == "GET" || _ == "DELETE" || _ == "HEAD" || _ == "OPTIONS" || _ == "POST" || _ == "PUT" || _ == "PATCH" || _ == "PURGE" || _ == "LINK" || _ == "UNLINK"'
    And match response.timestamp == '#regex \\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{3})?Z'

  Scenario: Test execution report with missing required parameters
    Given path '/test/event', 'trigger1', 'execute/report'
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 400
    And match response ==
      """
      {
        code: 400,
        timestamp: '#string',
        path: '/application/client/git/eaas/trigger',
        method: '#enum',
        message: '#string'
      }
      """
    And match response.method == '#? _ == "GET" || _ == "DELETE" || _ == "HEAD" || _ == "OPTIONS" || _ == "POST" || _ == "PUT" || _ == "PATCH" || _ == "PURGE" || _ == "LINK" || _ == "UNLINK"'
    And match response.timestamp == '#regex \\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{3})?Z'
