# ********RoostGPT********

# Test generated by RoostGPT for test test-roostapispec-1 using AI Type Claude AI and AI Model claude-3-5-sonnet-20240620
# 
# Feature file generated for /test/event/{trigger_id}/execute_post for http method type POST 
# RoostTestHash=b295bd765a
# 
# 

# ********RoostGPT********
Feature: Test GPT Controller - Execute Test

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * header Authorization = 'Bearer ' + authToken

  Scenario Outline: Execute test with valid trigger_id and request body
    Given path '/test/event', trigger_id, 'execute'
    And request
      """
      {
        "target_url": "<target_url>",
        "file_path": <file_path>,
        "env_config": <env_config>,
        "arrival_rate": <arrival_rate>,
        "duration": <duration>,
        "test_framework": "<test_framework>",
        "status_code": <status_code>,
        "csv_file_path": "<csv_file_path>",
        "endpoint": "<endpoint>"
      }
      """
    When method POST
    Then status 201
    And match response == {}

    Examples:
      | read('test_event_trigger_id_execute_post.csv') |

  Scenario: Execute test with invalid trigger_id
    Given path '/test/event', 'invalid_id', 'execute'
    And request
      """
      {
        "target_url": "http://example.com",
        "file_path": ["file1"]
      }
      """
    When method POST
    Then status 404
    And match response contains
      """
      {
        "code": 404,
        "timestamp": "#string",
        "path": "/test/event/invalid_id/execute",
        "method": "POST",
        "message": "Not found"
      }
      """

  Scenario: Execute test with missing required fields
    Given path '/test/event', 'test789', 'execute'
    And request
      """
      {
        "arrival_rate": 2,
        "duration": 5
      }
      """
    When method POST
    Then status 400
    And match response contains
      """
      {
        "code": 400,
        "timestamp": "#string",
        "path": "/test/event/test789/execute",
        "method": "POST",
        "message": "#string"
      }
      """

  Scenario: Execute test with invalid data types
    Given path '/test/event', 'test101', 'execute'
    And request
      """
      {
        "target_url": 123,
        "file_path": "not_an_array",
        "arrival_rate": "not_a_number",
        "duration": "invalid"
      }
      """
    When method POST
    Then status 400
    And match response contains
      """
      {
        "code": 400,
        "timestamp": "#string",
        "path": "/test/event/test101/execute",
        "method": "POST",
        "message": "#string"
      }
      """
