# ********RoostGPT********

# Test generated by RoostGPT for test testing-karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /insights/pages/{project-slug}/summary_get for http method type GET 
# RoostTestHash=d36b00fabb
# 
# 

# ********RoostGPT********
Feature: Insights API - Summary Metrics and Trends Retrieval

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Validate Summary Metrics using Circle-Token Authentication
    * def authToken = karate.properties['Circle-Token']
    * configure headers = { Circle-Token: '#(authToken)' }
    Given path 'insights/pages/<projectSlug>/summary'
    And param reporting-window = <reportingWindow>
    And param branches = <branches>
    And param workflow-names = <workflowNames>
    When method GET
    Then status 200
    And match response.org_id == '##string'
    And match response.project_id == '##string'
    And match response.project_data.metrics.total_runs == '#? _ == null || typeof _ == "number"'
    And match response.project_data.metrics.total_duration_secs == '#? _ == null || typeof _ == "number"'
    And match response.project_data.metrics.total_credits_used == '#? _ == null || typeof _ == "number"'
    And match response.project_data.metrics.success_rate == '#? _ == null || typeof _ == "number"'
    And match response.project_data.metrics.throughput == '#? _ == null || typeof _ == "number"'
    And match each response.project_workflow_data[*].workflow_name == '##string'
    And match each response.project_workflow_data[*].metrics.total_credits_used == '#? _ == null || typeof _ == "number"'
    And match each response.project_workflow_data[*].metrics.p95_duration_secs == '#? _ == null || typeof _ == "number"'
    And match each response.project_workflow_data[*].metrics.total_runs == '#? _ == null || typeof _ == "number"'
    And match each response.project_workflow_data[*].metrics.success_rate == '#? _ == null || typeof _ == "number"'
    And match each response.project_workflow_branch_data[*].workflow_name == '##string'
    And match each response.project_workflow_branch_data[*].branch == '##string'
    And match each response.project_workflow_branch_data[*].metrics.total_credits_used == '#? _ == null || typeof _ == "number"'
    And match each response.project_workflow_branch_data[*].metrics.p95_duration_secs == '#? _ == null || typeof _ == "number"'
    And match each response.project_workflow_branch_data[*].metrics.total_runs == '#? _ == null || typeof _ == "number"'
    And match each response.project_workflow_branch_data[*].metrics.success_rate == '#? _ == null || typeof _ == "number"'
    And match each response.all_workflows[*] == '##string'
    And match each response.all_branches[*] == '##string'

    Examples:
      | read('insights_pages_project-slug_summary_get.csv') |

  Scenario Outline: Validate Summary Metrics using Basic Authentication
    * def username = karate.properties['AUTH_USERNAME']
    * def password = karate.properties['AUTH_PASSWORD']
    * def credentials = username + ':' + password
    * def encoded = Java.type('java.util.Base64').getEncoder().encodeToString(credentials.getBytes())
    * def authHeader = 'Basic ' + encoded
    * configure headers = { Authorization: '#(authHeader)' }
    Given path 'insights/pages/<projectSlug>/summary'
    And param reporting-window = <reportingWindow>
    And param branches = <branches>
    And param workflow-names = <workflowNames>
    When method GET
    Then status 200
    And match response.org_id == '##string'
    And match response.project_id == '##string'
    And match response.project_data.metrics.total_runs == '#? _ == null || typeof _ == "number"'
    And match response.project_data.metrics.total_duration_secs == '#? _ == null || typeof _ == "number"'
    And match response.project_data.metrics.total_credits_used == '#? _ == null || typeof _ == "number"'
    And match response.project_data.metrics.success_rate == '#? _ == null || typeof _ == "number"'
    And match response.project_data.metrics.throughput == '#? _ == null || typeof _ == "number"'
    And match each response.project_workflow_data[*].workflow_name == '##string'
    And match each response.project_workflow_data[*].metrics.total_credits_used == '#? _ == null || typeof _ == "number"'
    And match each response.project_workflow_data[*].metrics.p95_duration_secs == '#? _ == null || typeof _ == "number"'
    And match each response.project_workflow_data[*].metrics.total_runs == '#? _ == null || typeof _ == "number"'
    And match each response.project_workflow_data[*].metrics.success_rate == '#? _ == null || typeof _ == "number"'
    And match each response.project_workflow_branch_data[*].workflow_name == '##string'
    And match each response.project_workflow_branch_data[*].branch == '##string'
    And match each response.project_workflow_branch_data[*].metrics.total_credits_used == '#? _ == null || typeof _ == "number"'
    And match each response.project_workflow_branch_data[*].metrics.p95_duration_secs == '#? _ == null || typeof _ == "number"'
    And match each response.project_workflow_branch_data[*].metrics.total_runs == '#? _ == null || typeof _ == "number"'
    And match each response.project_workflow_branch_data[*].metrics.success_rate == '#? _ == null || typeof _ == "number"'
    And match each response.all_workflows[*] == '##string'
    And match each response.all_branches[*] == '##string'

    Examples:
      | read('insights_pages_project-slug_summary_get.csv') |

  Scenario Outline: Validate Error Response with Invalid Path
    * def authToken = karate.properties['Circle-Token']
    * configure headers = { Circle-Token: '#(authToken)' }
    Given path 'insights/pages/<invalidProjectSlug>/summary'
    When method GET
    Then assert responseStatus != 200
    And match response.message == '##string'

    Examples:
      | invalidProjectSlug  |
      | 'invalid/slug/test' |
