// ********RoostGPT********
/*
Test generated by RoostGPT for test postman-test using AI Type Open AI and AI Model gpt-4

Test generated for /categories/{id}_put for http method type PUT in rest-assured framework

RoostTestHash=951091bedf


*/

// ********RoostGPT********

package com.bootexample4.RoostTest;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Before;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class categoriesIdPutTest {

    List<Map<String, String>> envList = new ArrayList<>();

    // Make sure to have the required dependencies in the local maven repository before running this test

    @Before
    public void setUp() {
      TestdataLoader dataloader = new TestdataLoader();
      envList = dataloader.loadData("src/test/java/com/bootexample4/RoostTest/categories_idPutTest.csv");
    }

    @Test  
    public void categoriesIdPut_Test() {
        this.setUp();
        for (Map<String, String> testData : envList) {
          RestAssured.baseURI = "http://localhost:8080/applicationPetstore/rest";  
  
                Response response = given()
                .when()
                .put("/categories/{id}")  
                .then() 
                .extract().response();    

                // Replace 'default' with the expected status code
                int expectedStatusCode = 200; // replace with the expected status code
                if (response.statusCode() == expectedStatusCode) {
					System.out.println("Description: successful operation");
				}
  
            }  
    }
}
