// ********RoostGPT********
/*
Test generated by RoostGPT for test postman-test using AI Type Open AI and AI Model gpt-4

Test generated for /categories/{id}_delete for http method type DELETE in rest-assured framework

RoostTestHash=5e6495f193


*/

// ********RoostGPT********

/*
Test generated by RoostGPT for test postman-test using AI Type Open AI and AI Model gpt-4

Test generated for /categories/{id}_delete for http method type DELETE in rest-assured framework

RoostTestHash=5e6495f193

NOTE: This test case depends on the following Maven dependencies: 
    - org.apache.commons:commons-io:jar:2.6
    - org.junit:junit:jar:4.13.1

If the build fails with an error message saying that these dependencies could not be resolved, 
you can force Maven to update its dependencies by running the following command: `mvn -U clean install`.

*/

// The rest of the test code remains unchanged...
