// ********RoostGPT********
/*
Test generated by RoostGPT for test postman-test using AI Type Open AI and AI Model gpt-4

Test generated for /customers_get for http method type GET in rest-assured framework

RoostTestHash=757c7bf7d8


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Before;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class customersGetTest {

        List<Map<String, String>> envList = new ArrayList<>();

        @Before
        public void setUp() {

                TestdataLoader dataloader = new TestdataLoader();
                String[] envVarsList = { "" };
                envList = dataloader.loadData(
                                "src/test/java/com/bootexample4/RoostTest/customersGetTest.csv", envVarsList);

        }

        @Test
        public void customersGet_Test() {
                this.setUp();
                for (Map<String, String> testData : envList) {

                        RestAssured.baseURI = "http://0.0.0.0:4012";

                        Response response = given()
                                        .queryParam("start", testData.get("start") != null ? testData.get("start") : "")
                                        .queryParam("max", testData.get("max") != null ? testData.get("max") : "")
                                        .when()
                                        .get("/customers")
                                        .then()
                                        .extract().response();

                        System.out.println(response.getBody().asString());
                        System.out.println(response.statusCode());

                        if (response.statusCode() == 200) {
                                System.out.println("Description: successful operation");

                                // if (response.xmlPath().get("id") != null) {
                                // MatcherAssert.assertThat(response.xmlPath().getString("id"),
                                // instanceOf(Integer.class));
                                // }

                                // if (response.xmlPath().get("version") != null) {
                                // MatcherAssert.assertThat(response.xmlPath().getString("version"),
                                // instanceOf(Integer.class));
                                // }

                                if (response.xmlPath().get("firstName") != null) {
                                        MatcherAssert.assertThat(response.xmlPath().getString("firstName"),
                                                        instanceOf(String.class));
                                        MatcherAssert.assertThat(response.xmlPath().getString("firstName").length(),
                                                        greaterThanOrEqualTo(50));

                                        MatcherAssert.assertThat(response.xmlPath().getString("firstName").length(),
                                                        greaterThanOrEqualTo(2));

                                }

                                if (response.xmlPath().get("lastName") != null) {
                                        MatcherAssert.assertThat(response.xmlPath().getString("lastName"),
                                                        instanceOf(String.class));
                                        MatcherAssert.assertThat(response.xmlPath().getString("lastName").length(),
                                                        greaterThanOrEqualTo(50));

                                        MatcherAssert.assertThat(response.xmlPath().getString("lastName").length(),
                                                        greaterThanOrEqualTo(2));

                                }

                                if (response.xmlPath().get("telephone") != null) {
                                        MatcherAssert.assertThat(response.xmlPath().getString("telephone"),
                                                        instanceOf(String.class));
                                }

                                if (response.xmlPath().get("email") != null) {
                                        MatcherAssert.assertThat(response.xmlPath().getString("email"),
                                                        instanceOf(String.class));
                                }

                                if (response.xmlPath().get("login") != null) {
                                        MatcherAssert.assertThat(response.xmlPath().getString("login"),
                                                        instanceOf(String.class));
                                }

                                if (response.xmlPath().get("password") != null) {
                                        MatcherAssert.assertThat(response.xmlPath().getString("password"),
                                                        instanceOf(String.class));
                                        MatcherAssert.assertThat(response.xmlPath().getString("password").length(),
                                                        lessThanOrEqualTo(256));

                                        MatcherAssert.assertThat(response.xmlPath().getString("password").length(),
                                                        greaterThanOrEqualTo(1));

                                }

                                if (response.xmlPath().get("uuid") != null) {
                                        MatcherAssert.assertThat(response.xmlPath().getString("uuid"),
                                                        instanceOf(String.class));
                                        MatcherAssert.assertThat(response.xmlPath().getString("uuid").length(),
                                                        lessThanOrEqualTo(256));

                                        MatcherAssert.assertThat(response.xmlPath().getString("uuid").length(),
                                                        greaterThanOrEqualTo(1));

                                }

                                if (response.xmlPath().get("role") != null) {
                                        MatcherAssert.assertThat(response.xmlPath().getString("role"),
                                                        instanceOf(String.class));
                                        System.out.println(response.xmlPath().getString("role"));
                                        // MatcherAssert.assertThat(response.xmlPath().getString("role"),
                                        // anyOf(equalTo("USER"), equalTo("ADMIN")));

                                }

                                if (response.xmlPath().get("dateOfBirth") != null) {
                                        MatcherAssert.assertThat(response.xmlPath().getString("dateOfBirth"),
                                                        instanceOf(String.class));
                                }

                                if (response.xmlPath().get("age") != null) {
                                        // MatcherAssert.assertThat(response.xmlPath().get("age"),
                                        // instanceOf(Integer.class));
                                }

                                if (response.xmlPath().get("homeAddress") != null) {
                                        if (response.xmlPath().get("homeAddress.street1") != null) {
                                                MatcherAssert.assertThat(
                                                                response.xmlPath().getString("homeAddress.street1"),
                                                                instanceOf(String.class));
                                                MatcherAssert.assertThat(
                                                                response.xmlPath().getString("homeAddress.street1")
                                                                                .length(),
                                                                lessThanOrEqualTo(50));

                                                MatcherAssert.assertThat(
                                                                response.xmlPath().getString("homeAddress.street1")
                                                                                .length(),
                                                                lessThanOrEqualTo(5));

                                        }

                                        if (response.xmlPath().get("homeAddress.street2") != null) {
                                                MatcherAssert.assertThat(
                                                                response.xmlPath().getString("homeAddress.street2"),
                                                                instanceOf(String.class));
                                        }

                                        if (response.xmlPath().get("homeAddress.city") != null) {
                                                MatcherAssert.assertThat(
                                                                response.xmlPath().getString("homeAddress.city"),
                                                                instanceOf(String.class));
                                                MatcherAssert.assertThat(
                                                                response.xmlPath().getString("homeAddress.city")
                                                                                .length(),
                                                                lessThanOrEqualTo(50));

                                                MatcherAssert.assertThat(
                                                                response.xmlPath().getString("homeAddress.city")
                                                                                .length(),
                                                                lessThanOrEqualTo(2));

                                        }

                                        if (response.xmlPath().get("homeAddress.state") != null) {
                                                MatcherAssert.assertThat(
                                                                response.xmlPath().getString("homeAddress.state"),
                                                                instanceOf(String.class));
                                        }

                                        if (response.xmlPath().get("homeAddress.zipcode") != null) {
                                                MatcherAssert.assertThat(
                                                                response.xmlPath().getString("homeAddress.zipcode"),
                                                                instanceOf(String.class));
                                                MatcherAssert.assertThat(
                                                                response.xmlPath().getString("homeAddress.zipcode")
                                                                                .length(),
                                                                lessThanOrEqualTo(10));

                                                MatcherAssert.assertThat(
                                                                response.xmlPath().getString("homeAddress.zipcode")
                                                                                .length(),
                                                                lessThanOrEqualTo(1));

                                        }

                                        if (response.xmlPath().get("homeAddress.country") != null) {
                                                if (response.xmlPath().get("homeAddress.country.id") != null) {
                                                        // MatcherAssert.assertThat(
                                                        // response.xmlPath()
                                                        // .get("homeAddress.country.id"),
                                                        // instanceOf(Integer.class));
                                                }

                                                if (response.xmlPath().get("homeAddress.country.version") != null) {
                                                        // MatcherAssert.assertThat(
                                                        // response.xmlPath().get(
                                                        // "homeAddress.country.version"),
                                                        // instanceOf(Integer.class));
                                                }

                                                if (response.xmlPath().get("homeAddress.country.isoCode") != null) {
                                                        MatcherAssert.assertThat(
                                                                        response.xmlPath().getString(
                                                                                        "homeAddress.country.isoCode"),
                                                                        instanceOf(String.class));
                                                        MatcherAssert.assertThat(
                                                                        response.xmlPath().getString(
                                                                                        "homeAddress.country.isoCode")
                                                                                        .length(),
                                                                        lessThanOrEqualTo(2));

                                                        MatcherAssert.assertThat(
                                                                        response.xmlPath().getString(
                                                                                        "homeAddress.country.isoCode")
                                                                                        .length(),
                                                                        lessThanOrEqualTo(2));

                                                }

                                                if (response.xmlPath().get("homeAddress.country.name") != null) {
                                                        MatcherAssert.assertThat(
                                                                        response.xmlPath().getString(
                                                                                        "homeAddress.country.name"),
                                                                        instanceOf(String.class));
                                                        MatcherAssert.assertThat(response.xmlPath()
                                                                        .getString("homeAddress.country.name").length(),
                                                                        lessThanOrEqualTo(80));

                                                        MatcherAssert.assertThat(response.xmlPath()
                                                                        .getString("homeAddress.country.name").length(),
                                                                        lessThanOrEqualTo(2));

                                                }

                                                if (response.xmlPath()
                                                                .get("homeAddress.country.printableName") != null) {
                                                        MatcherAssert.assertThat(response.xmlPath()
                                                                        .getString("homeAddress.country.printableName"),
                                                                        instanceOf(String.class));
                                                        MatcherAssert.assertThat(
                                                                        response.xmlPath().getString(
                                                                                        "homeAddress.country.printableName")
                                                                                        .length(),
                                                                        lessThanOrEqualTo(80));

                                                        MatcherAssert.assertThat(
                                                                        response.xmlPath().getString(
                                                                                        "homeAddress.country.printableName")
                                                                                        .length(),
                                                                        lessThanOrEqualTo(2));

                                                }

                                                if (response.xmlPath().get("homeAddress.country.iso3") != null) {
                                                        MatcherAssert.assertThat(
                                                                        response.xmlPath().getString(
                                                                                        "homeAddress.country.iso3"),
                                                                        instanceOf(String.class));
                                                        MatcherAssert.assertThat(response.xmlPath()
                                                                        .getString("homeAddress.country.iso3").length(),
                                                                        lessThanOrEqualTo(3));

                                                        MatcherAssert.assertThat(response.xmlPath()
                                                                        .getString("homeAddress.country.iso3").length(),
                                                                        lessThanOrEqualTo(3));

                                                }

                                                if (response.xmlPath().get("homeAddress.country.numcode") != null) {
                                                        MatcherAssert.assertThat(
                                                                        response.xmlPath().getString(
                                                                                        "homeAddress.country.numcode"),
                                                                        instanceOf(String.class));
                                                        MatcherAssert.assertThat(
                                                                        response.xmlPath().getString(
                                                                                        "homeAddress.country.numcode")
                                                                                        .length(),
                                                                        lessThanOrEqualTo(3));

                                                        MatcherAssert.assertThat(
                                                                        response.xmlPath().getString(
                                                                                        "homeAddress.country.numcode")
                                                                                        .length(),
                                                                        lessThanOrEqualTo(3));

                                                }

                                        }

                                }

                                if (response.xmlPath().get("fullName") != null) {
                                        MatcherAssert.assertThat(response.xmlPath().getString("fullName"),
                                                        instanceOf(String.class));
                                }
                        }

                }
        }
}