// Test generated by RoostGPT for test Koreai-restassured using AI Type Open AI and AI Model gpt-4-1106-preview

// Test generated for /deposit_post for http method type POST in rest-assured framework

// RoostTestHash=70db6d5eac

private void validateBadRequestResponse(Response response) {
  // Expected keys in the response JSON for status code 400
  assertThat(response.jsonPath().getString("error"), notNullValue());
  assertThat(response.jsonPath().getString("error_description"), notNullValue());
  // You can add more specific checks, depending on the actual response structure
}

private void validateErrorResponse(Response response) {
  // Expected keys in the response JSON for status code 401
  assertThat(response.jsonPath().getString("error"), equalTo("unauthorized"));
  assertThat(response.jsonPath().getString("error_description"), containsString("invalid credentials"));
  // More checks...
}

private void validateNotFoundResponse(Response response) {
  // Expected keys in the response JSON for status code 404
  assertThat(response.jsonPath().getString("error"), equalTo("not_found"));
  // More checks...
}

private void validateUnprocessableEntityResponse(Response response) {
  // Expected keys in the response JSON for status code 422
  assertThat(response.jsonPath().get("errors"), hasSize(greaterThan(0)));
  // Iterate through the errors if it's an array and assert the structure
  // More checks...
}

