// ********RoostGPT********
/*
Test generated by RoostGPT for test postman-test using AI Type Open AI and AI Model gpt-4

Test generated for /embeddings_post for http method type POST in rest-assured framework

RoostTestHash=b6b8c85368


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Before;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class embeddingsPostTest {

    List<Map<String, String>> envList = new ArrayList<>();


    @Before
    public void setUp() {
      TestdataLoader dataloader = new TestdataLoader();
      envList = dataloader.loadData("src/test/java/com/bootexample4/RoostTest/embeddingsPostTest.csv");
    }

  
    @Test  
    public void embeddingsPost_Test() {
        this.setUp();
        for (Map<String, String> testData : envList) {
          RestAssured.baseURI = "https://api.openai.com/v1";  
  
                Response response = given()
				.contentType(ContentType.JSON)
				.body("{\n"+
					"  \"input\": \"" + (testData.get("input") != null ? testData.get("input") : "") + "\",\n" +
					"  \"model\": \"" + (testData.get("model") != null ? testData.get("model") : "") + "\",\n" +
					"  \"encoding_format\": \"" + (testData.get("encoding_format") != null ? testData.get("encoding_format") : "") + "\",\n" +
					"  \"dimensions\": \"" + (testData.get("dimensions") != null ? testData.get("dimensions") : "") + "\",\n" +
					"  \"user\": \"" + (testData.get("user") != null ? testData.get("user") : "") + "\n" +
 				"}")
				.header("api_key", testData.get("api_key"))
                .when()
                .post("/embeddings")  
                .then() 
                .extract().response();    
         
                if (response.statusCode() == 200) {
					System.out.println("Description: OK");
      
              if (response.jsonPath().get("data") != null) {      
                for (int i = 0; i < response.jsonPath().getList("data").size(); i++) {      
              if (response.jsonPath().get("data["+ i +"].index") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("data["+ i +"].index"), instanceOf(Integer.class));  
          }
      
              if (response.jsonPath().get("data["+ i +"].embedding") != null) {      
                for (int i1 = 0; i1 < response.jsonPath().getList("data["+ i +"].embedding").size(); i1++) {      
                  }    
                MatcherAssert.assertThat(response.jsonPath().getList("data["+ i +"].embedding"), instanceOf(List.class));
  
          }
      
              if (response.jsonPath().get("data["+ i +"].object") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("data["+ i +"].object"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("data["+ i +"].object"), anyOf(equalTo("embedding")));
  
          }
      
                  }    
                MatcherAssert.assertThat(response.jsonPath().getList("data"), instanceOf(List.class));
  
          }
      
              if (response.jsonPath().get("model") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("model"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("object") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("object"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("object"), anyOf(equalTo("list")));
  
          }
      
              if (response.jsonPath().get("usage") != null) {      
              if (response.jsonPath().get("usage.prompt_tokens") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("usage.prompt_tokens"), instanceOf(Integer.class));  
          }
      
              if (response.jsonPath().get("usage.total_tokens") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("usage.total_tokens"), instanceOf(Integer.class));  
          }
  
          }
				}
  
            }  
    }
}
