// ********RoostGPT********
/*
Test generated by RoostGPT for test Test-5619 using AI Type  and AI Model 

Test generated for /forms/{form-type}/{form-instance-id}_put for http method type PUT in rest-assured framework

RoostTestHash=62e0da3209


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;
import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.json.JSONObject;
import org.json.XML;
import org.json.JSONException;
import org.json.JSONArray;
import java.util.Arrays;

public class formsFormtypeForminstanceidPutTest {

    List<Map<String, String>> envList = new ArrayList<>();


    @BeforeEach
    public void setUp() {
      TestdataLoader dataloader = new TestdataLoader();
      String[] envVarsList = {"form-type", "form-instance-id"};
      envList = dataloader.load("src/test/java/com/bootexample4/RoostTest/forms_form-type_form-instance-idPutTest.csv", envVarsList);
    }

  
    @Test  
    public void formsFormtypeForminstanceidPut_Test() throws JSONException {
        this.setUp();
        Integer testNumber = 1;
        for (Map<String, String> testData : envList) {
          RestAssured.baseURI = (testData.get("BASE_URL") != null && !testData.get("BASE_URL").isEmpty()) ? testData.get("BASE_URL"): "https://stoplight.io/mocks/hsbc/sandbox/43741497";  
          JSONObject requestBodyObject = new JSONObject();
          if(testData.get("RequestBody") != null){
              requestBodyObject = new JSONObject(testData.get("RequestBody"));
          }
                Response responseObj = given()
				.header("Authorization", testData.get("Authorization") != null ? testData.get("Authorization") : "")
				.header("X-HSBC-Request-Correlation-Id", testData.get("X-HSBC-Request-Correlation-Id") != null ? testData.get("X-HSBC-Request-Correlation-Id") : "")
				.pathParam("form-type", testData.get("form-type") != null ? testData.get("form-type") : "")
				.pathParam("form-instance-id", testData.get("form-instance-id") != null ? testData.get("form-instance-id") : "")
				.contentType(ContentType.JSON)
				.body(requestBodyObject.toString())
                .when()
                .put("/forms/{form-type}/{form-instance-id}")  
                .then() 
                .extract().response(); 
              JsonPath response;
              String contentType = responseObj.getContentType();

              System.out.printf("Test Case %d: formsFormtypeForminstanceidPut_Test \n", testNumber++);
              System.out.println("Request: PUT /forms/{form-type}/{form-instance-id}");
              System.out.println("Status Code: " + responseObj.statusCode());
              if (testData.get("statusCode") != null) {
                String statusCodeFromCSV = testData.get("statusCode");
                if (statusCodeFromCSV.contains("X")) {
                  MatcherAssert.assertThat(
                      "Expected a status code of category " + statusCodeFromCSV + ", but got "
                          + Integer.toString(responseObj.statusCode()) + " instead",
                      Integer.toString(responseObj.statusCode()).charAt(0), equalTo(statusCodeFromCSV.charAt(0)));
                } else {
                  MatcherAssert.assertThat(
                      Integer.toString(responseObj.statusCode()), equalTo(statusCodeFromCSV));
                }
              } 
              				else {  
      List<Integer> expectedStatusCodes = Arrays.asList(200,400,500);
				MatcherAssert.assertThat(responseObj.statusCode(), is(in(expectedStatusCodes)));
          }
				String stringifiedStatusCode = Integer.toString(responseObj.statusCode());
        switch(responseObj.statusCode()){
        
          case 200:
            stringifiedStatusCode = "200";
            MatcherAssert.assertThat(contentType, equalTo("application/json"));
            break;
         
          case 400:
            stringifiedStatusCode = "400";
            MatcherAssert.assertThat(contentType, equalTo("application/json"));
            break;
         
          case 500:
            stringifiedStatusCode = "500";
            MatcherAssert.assertThat(contentType, equalTo("application/json"));
            break;
         
    }

      switch(Integer.toString(responseObj.statusCode()).charAt(0)){
      
    }

      
              if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
                String xmlResponse = responseObj.asString();
                JSONObject jsonResponse = XML.toJSONObject(xmlResponse);
                JSONObject jsonData = jsonResponse.getJSONObject("xml");
                String jsonString = jsonData.toString();
                response = new JsonPath(jsonString);
        
              } else if(contentType.contains("application/json")){  
                response = responseObj.jsonPath(); 
              } else {
                System.out.println("Response content type found: "+contentType+", but RoostGPT currently only supports the following response content types: application/json,text/xml,application/xml");
                continue;
              }
         
                if(stringifiedStatusCode.equals("200")){					System.out.println("Description: Successful Evaluation");
      
              if (response.get("status") != null) {
                  
                MatcherAssert.assertThat(response.get("status"), instanceOf(String.class));
              }
      
              if (response.get("messages") != null) {
                      
              if (response.get("messages.information") != null) {
                        
                  for (int i = 0; i < response.getList("messages.information").size(); i++) {        
                    }    
                MatcherAssert.assertThat(response.getList("messages.information"), instanceOf(List.class));

              }
      
              if (response.get("messages.warning") != null) {
                        
                  for (int i = 0; i < response.getList("messages.warning").size(); i++) {        
                    }    
                MatcherAssert.assertThat(response.getList("messages.warning"), instanceOf(List.class));

              }
      
              if (response.get("messages.error") != null) {
                        
                  for (int i = 0; i < response.getList("messages.error").size(); i++) {        
                    }    
                MatcherAssert.assertThat(response.getList("messages.error"), instanceOf(List.class));

              }
      
              if (response.get("messages.generalError") != null) {
                  
                MatcherAssert.assertThat(response.get("messages.generalError"), instanceOf(String.class));
              }

              }
      
              if (response.get("currentViewId") != null) {
                  
                MatcherAssert.assertThat(response.get("currentViewId"), instanceOf(String.class));
              }
      
              if (response.get("nextViewId") != null) {
                  
                MatcherAssert.assertThat(response.get("nextViewId"), instanceOf(String.class));
              }
      
              if (response.get("domainSessionId") != null) {
                  
                MatcherAssert.assertThat(response.get("domainSessionId"), instanceOf(String.class));
              }
      
              if (response.get("views") != null) {
                        
                  for (int i = 0; i < response.getList("views").size(); i++) {      
              if (response.get("views["+ i +"].form-instance-id") != null) {
                  
                MatcherAssert.assertThat(response.get("views["+ i +"].form-instance-id"), instanceOf(String.class));
              }
      
              if (response.get("views["+ i +"].status") != null) {
                  
                MatcherAssert.assertThat(response.get("views["+ i +"].status"), instanceOf(String.class));
              }
      
              if (response.get("views["+ i +"].mode") != null) {
                  
                MatcherAssert.assertThat(response.get("views["+ i +"].mode"), instanceOf(String.class));
              }
      
              if (response.get("views["+ i +"].nextViewId") != null) {
                  
                MatcherAssert.assertThat(response.get("views["+ i +"].nextViewId"), instanceOf(String.class));
              }
      
              if (response.get("views["+ i +"].title") != null) {
                  
                MatcherAssert.assertThat(response.get("views["+ i +"].title"), instanceOf(String.class));
              }
      
              if (response.get("views["+ i +"].completed") != null) {
                  
                MatcherAssert.assertThat(response.get("views["+ i +"].completed"), instanceOf(Boolean.class));
              }
      
              if (response.get("views["+ i +"].errors") != null) {
                  
                MatcherAssert.assertThat(response.get("views["+ i +"].errors"), instanceOf(Boolean.class));
              }
      
              if (response.get("views["+ i +"].visibleRule") != null) {
                  
                MatcherAssert.assertThat(response.get("views["+ i +"].visibleRule"), instanceOf(String.class));
              }
      
              if (response.get("views["+ i +"].nextViewIdRule") != null) {
                  
                MatcherAssert.assertThat(response.get("views["+ i +"].nextViewIdRule"), instanceOf(String.class));
              }
      
              if (response.get("views["+ i +"].items") != null) {
                        
                  for (int i1 = 0; i1 < response.getList("views["+ i +"].items").size(); i1++) {      
              if (response.get("views["+ i +"].items["+ i1 +"].form-instance-id") != null) {
                  
                MatcherAssert.assertThat(response.get("views["+ i +"].items["+ i1 +"].form-instance-id"), instanceOf(String.class));
              }
      
              if (response.get("views["+ i +"].items["+ i1 +"].type") != null) {
                  
                MatcherAssert.assertThat(response.get("views["+ i +"].items["+ i1 +"].type"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.getString("views["+ i +"].items["+ i1 +"].type"), anyOf(equalTo("QUESTION"), equalTo("LEFT_NAV_MENU"), equalTo("SECTION"), equalTo("TEXT"), equalTo("ACTIONS"), equalTo("NOTIFICATION"), equalTo("PROCESS_COMPLETE"), equalTo("INVALID")));

              }
      
              if (response.get("views["+ i +"].items["+ i1 +"].status") != null) {
                  
                MatcherAssert.assertThat(response.get("views["+ i +"].items["+ i1 +"].status"), instanceOf(String.class));
              }
      
              if (response.get("views["+ i +"].items["+ i1 +"].parentId") != null) {
                  
                MatcherAssert.assertThat(response.get("views["+ i +"].items["+ i1 +"].parentId"), instanceOf(String.class));
              }
        
                    }    
                MatcherAssert.assertThat(response.getList("views["+ i +"].items"), instanceOf(List.class));

              }
      
              if (response.get("views["+ i +"].parentId") != null) {
                  
                MatcherAssert.assertThat(response.get("views["+ i +"].parentId"), instanceOf(String.class));
              }
        
                    }    
                MatcherAssert.assertThat(response.getList("views"), instanceOf(List.class));

              }
      
              if (response.get("count") != null) {
                  
                MatcherAssert.assertThat(response.get("count"), instanceOf(Integer.class));
              }
				}
if(stringifiedStatusCode.equals("400")){					System.out.println("Description: Bad Request Response");
      
              if (response.get("type") != null) {
                  
                MatcherAssert.assertThat(response.get("type"), instanceOf(String.class));
              }
      
              if (response.get("title") != null) {
                  
                MatcherAssert.assertThat(response.get("title"), instanceOf(String.class));
              }
      
              if (response.get("status") != null) {
                  
                MatcherAssert.assertThat(response.get("status"), instanceOf(String.class));
              }
      
              if (response.get("detail") != null) {
                  
                MatcherAssert.assertThat(response.get("detail"), instanceOf(String.class));
              }
      
              if (response.get("errors") != null) {
                        
                  for (int i = 0; i < response.getList("errors").size(); i++) {      
              if (response.get("errors["+ i +"].type") != null) {
                  
                MatcherAssert.assertThat(response.get("errors["+ i +"].type"), instanceOf(String.class));
              }
      
              if (response.get("errors["+ i +"].detail") != null) {
                  
                MatcherAssert.assertThat(response.get("errors["+ i +"].detail"), instanceOf(String.class));
              }
        
                    }    
                MatcherAssert.assertThat(response.getList("errors"), instanceOf(List.class));

              }
      
              if (response.get("instance") != null) {
                  
                MatcherAssert.assertThat(response.get("instance"), instanceOf(String.class));
              }
      
              if (response.get("errorDateTime") != null) {
                  
                MatcherAssert.assertThat(response.get("errorDateTime"), instanceOf(String.class));
              }
				}
if(stringifiedStatusCode.equals("500")){					System.out.println("Description: Internal Server Error Response");
      
              if (response.get("type") != null) {
                  
                MatcherAssert.assertThat(response.get("type"), instanceOf(String.class));
              }
      
              if (response.get("title") != null) {
                  
                MatcherAssert.assertThat(response.get("title"), instanceOf(String.class));
              }
      
              if (response.get("status") != null) {
                  
                MatcherAssert.assertThat(response.get("status"), instanceOf(String.class));
              }
      
              if (response.get("detail") != null) {
                  
                MatcherAssert.assertThat(response.get("detail"), instanceOf(String.class));
              }
      
              if (response.get("errors") != null) {
                        
                  for (int i = 0; i < response.getList("errors").size(); i++) {      
              if (response.get("errors["+ i +"].type") != null) {
                  
                MatcherAssert.assertThat(response.get("errors["+ i +"].type"), instanceOf(String.class));
              }
      
              if (response.get("errors["+ i +"].detail") != null) {
                  
                MatcherAssert.assertThat(response.get("errors["+ i +"].detail"), instanceOf(String.class));
              }
        
                    }    
                MatcherAssert.assertThat(response.getList("errors"), instanceOf(List.class));

              }
      
              if (response.get("instance") != null) {
                  
                MatcherAssert.assertThat(response.get("instance"), instanceOf(String.class));
              }
      
              if (response.get("errorDateTime") != null) {
                  
                MatcherAssert.assertThat(response.get("errorDateTime"), instanceOf(String.class));
              }
				}


            }  
    }
}
