// ********RoostGPT********
/*
Test generated by RoostGPT for test postman-test using AI Type Open AI and AI Model gpt-4

Test generated for /fine_tuning/jobs_post for http method type POST in rest-assured framework

RoostTestHash=b722e625f7


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Before;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class jobsPostTest {

    List<Map<String, String>> envList = new ArrayList<>();


    @Before
    public void setUp() {
      TestdataLoader dataloader = new TestdataLoader();
      envList = dataloader.loadData("src/test/java/com/bootexample4/RoostTest/jobsPostTest.csv");
    }

  
    @Test  
    public void jobsPost_Test() {
        this.setUp();
        for (Map<String, String> testData : envList) {
          RestAssured.baseURI = "https://api.openai.com/v1";  
  
                Response response = given()
				.contentType(ContentType.JSON)
				.body("{\n"+
					"  \"model\": \"" + (testData.get("model") != null ? testData.get("model") : "") + "\",\n" +
					"  \"training_file\": \"" + (testData.get("training_file") != null ? testData.get("training_file") : "") + "\",\n" +
					"  \"hyperparameters\": \"" + (testData.get("hyperparameters") != null ? testData.get("hyperparameters") : "") + "\",\n" +
					"  \"suffix\": \"" + (testData.get("suffix") != null ? testData.get("suffix") : "") + "\",\n" +
					"  \"validation_file\": \"" + (testData.get("validation_file") != null ? testData.get("validation_file") : "") + "\n" +
 				"}")
				.header("api_key", testData.get("api_key"))
                .when()
                .post("/fine_tuning/jobs")  
                .then() 
                .extract().response();    
         
                if (response.statusCode() == 200) {
					System.out.println("Description: OK");
      
              if (response.jsonPath().get("id") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("id"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("created_at") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("created_at"), instanceOf(Integer.class));  
          }
      
              if (response.jsonPath().get("error") != null) {      
              if (response.jsonPath().get("error.code") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("error.code"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("error.message") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("error.message"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("error.param") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("error.param"), instanceOf(String.class));  
          }
  
          }
      
              if (response.jsonPath().get("fine_tuned_model") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("fine_tuned_model"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("finished_at") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("finished_at"), instanceOf(Integer.class));  
          }
      
              if (response.jsonPath().get("hyperparameters") != null) {      
              if (response.jsonPath().get("hyperparameters.n_epochs") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("hyperparameters.n_epochs"), instanceOf(undefined.class));  
          }
  
          }
      
              if (response.jsonPath().get("model") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("model"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("object") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("object"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("object"), anyOf(equalTo("fine_tuning.job")));
  
          }
      
              if (response.jsonPath().get("organization_id") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("organization_id"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("result_files") != null) {      
                for (int i = 0; i < response.jsonPath().getList("result_files").size(); i++) {      
                  }    
                MatcherAssert.assertThat(response.jsonPath().getList("result_files"), instanceOf(List.class));
  
          }
      
              if (response.jsonPath().get("status") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("status"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.jsonPath().getString("status"), anyOf(equalTo("validating_files"), equalTo("queued"), equalTo("running"), equalTo("succeeded"), equalTo("failed"), equalTo("cancelled")));
  
          }
      
              if (response.jsonPath().get("trained_tokens") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("trained_tokens"), instanceOf(Integer.class));  
          }
      
              if (response.jsonPath().get("training_file") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("training_file"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("validation_file") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("validation_file"), instanceOf(String.class));  
          }
				}
  
            }  
    }
}
