// ********RoostGPT********
/*
Test generated by RoostGPT for test postman-test using AI Type Open AI and AI Model gpt-4

Test generated for /moderations_post for http method type POST in rest-assured framework

RoostTestHash=19d1081633


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Before;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class moderationsPostTest {

    List<Map<String, String>> envList = new ArrayList<>();


    @Before
    public void setUp() {
      TestdataLoader dataloader = new TestdataLoader();
      envList = dataloader.loadData("src/test/java/com/bootexample4/RoostTest/moderationsPostTest.csv");
    }

  
    @Test  
    public void moderationsPost_Test() {
        this.setUp();
        for (Map<String, String> testData : envList) {
          RestAssured.baseURI = "https://api.openai.com/v1";  
  
                Response response = given()
				.contentType(ContentType.JSON)
				.body("{\n"+
					"  \"input\": \"" + (testData.get("input") != null ? testData.get("input") : "") + "\",\n" +
					"  \"model\": \"" + (testData.get("model") != null ? testData.get("model") : "") + "\n" +
 				"}")
				.header("api_key", testData.get("api_key"))
                .when()
                .post("/moderations")  
                .then() 
                .extract().response();    
         
                if (response.statusCode() == 200) {
					System.out.println("Description: OK");
      
              if (response.jsonPath().get("id") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("id"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("model") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("model"), instanceOf(String.class));  
          }
      
              if (response.jsonPath().get("results") != null) {      
                for (int i = 0; i < response.jsonPath().getList("results").size(); i++) {      
              if (response.jsonPath().get("results["+ i +"].flagged") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].flagged"), instanceOf(Boolean.class));  
          }
      
              if (response.jsonPath().get("results["+ i +"].categories") != null) {      
              if (response.jsonPath().get("results["+ i +"].categories.hate") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].categories.hate"), instanceOf(Boolean.class));  
          }
      
              if (response.jsonPath().get("results["+ i +"].categories.hate/threatening") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].categories.hate/threatening"), instanceOf(Boolean.class));  
          }
      
              if (response.jsonPath().get("results["+ i +"].categories.harassment") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].categories.harassment"), instanceOf(Boolean.class));  
          }
      
              if (response.jsonPath().get("results["+ i +"].categories.harassment/threatening") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].categories.harassment/threatening"), instanceOf(Boolean.class));  
          }
      
              if (response.jsonPath().get("results["+ i +"].categories.self-harm") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].categories.self-harm"), instanceOf(Boolean.class));  
          }
      
              if (response.jsonPath().get("results["+ i +"].categories.self-harm/intent") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].categories.self-harm/intent"), instanceOf(Boolean.class));  
          }
      
              if (response.jsonPath().get("results["+ i +"].categories.self-harm/instructions") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].categories.self-harm/instructions"), instanceOf(Boolean.class));  
          }
      
              if (response.jsonPath().get("results["+ i +"].categories.sexual") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].categories.sexual"), instanceOf(Boolean.class));  
          }
      
              if (response.jsonPath().get("results["+ i +"].categories.sexual/minors") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].categories.sexual/minors"), instanceOf(Boolean.class));  
          }
      
              if (response.jsonPath().get("results["+ i +"].categories.violence") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].categories.violence"), instanceOf(Boolean.class));  
          }
      
              if (response.jsonPath().get("results["+ i +"].categories.violence/graphic") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].categories.violence/graphic"), instanceOf(Boolean.class));  
          }
  
          }
      
              if (response.jsonPath().get("results["+ i +"].category_scores") != null) {      
              if (response.jsonPath().get("results["+ i +"].category_scores.hate") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].category_scores.hate"), instanceOf(Integer.class));  
          }
      
              if (response.jsonPath().get("results["+ i +"].category_scores.hate/threatening") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].category_scores.hate/threatening"), instanceOf(Integer.class));  
          }
      
              if (response.jsonPath().get("results["+ i +"].category_scores.harassment") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].category_scores.harassment"), instanceOf(Integer.class));  
          }
      
              if (response.jsonPath().get("results["+ i +"].category_scores.harassment/threatening") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].category_scores.harassment/threatening"), instanceOf(Integer.class));  
          }
      
              if (response.jsonPath().get("results["+ i +"].category_scores.self-harm") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].category_scores.self-harm"), instanceOf(Integer.class));  
          }
      
              if (response.jsonPath().get("results["+ i +"].category_scores.self-harm/intent") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].category_scores.self-harm/intent"), instanceOf(Integer.class));  
          }
      
              if (response.jsonPath().get("results["+ i +"].category_scores.self-harm/instructions") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].category_scores.self-harm/instructions"), instanceOf(Integer.class));  
          }
      
              if (response.jsonPath().get("results["+ i +"].category_scores.sexual") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].category_scores.sexual"), instanceOf(Integer.class));  
          }
      
              if (response.jsonPath().get("results["+ i +"].category_scores.sexual/minors") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].category_scores.sexual/minors"), instanceOf(Integer.class));  
          }
      
              if (response.jsonPath().get("results["+ i +"].category_scores.violence") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].category_scores.violence"), instanceOf(Integer.class));  
          }
      
              if (response.jsonPath().get("results["+ i +"].category_scores.violence/graphic") != null) {  
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].category_scores.violence/graphic"), instanceOf(Integer.class));  
          }
  
          }
      
                  }    
                MatcherAssert.assertThat(response.jsonPath().getList("results"), instanceOf(List.class));
  
          }
				}
  
            }  
    }
}
