// Test generated by RoostGPT for test test-postman1 using AI Type Open AI and AI Model gpt-4-1106-preview


// Test generated for /order-report/meta-data/order-types_get for http method type GET in rest-assured framework


// RoostTestHash=e5a6af5c86


package com.bootexample4.RoostTest;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class orderTypesGetTest {
  
    @Test  
    public void orderTypesGet_Test() {  
        RestAssured.baseURI = System.getenv("BASE_URL");  
  
        // Read CSV file  
        try (BufferedReader reader = new BufferedReader(new FileReader("src" + File.separator + "test" + File.separator + "java" + File.separator + "com" + File.separator + "bootexample4" + File.separator + "RoostTest" + File.separator + "order-typesGetTest.csv"))) {  
            String headerLine = reader.readLine();  
            String[] headers = headerLine.split(",");  
  
            String line;  
            while ((line = reader.readLine()) != null) {  
                String[] data = line.split(",");  
  
                // Create a map of header to data  
                Map<String, String> map = new HashMap<>();  
                for (int i = 0; i < headers.length; i++) {  
                    map.put(headers[i], data[i]);  
                }  
                
  
                Response response = given()
				.pathParam("X-Trace-Id", map.get("X-Trace-Id") != null ? map.get("X-Trace-Id") : "")
				.pathParam("channel", map.get("channel") != null ? map.get("channel") : "")
				.pathParam("username", map.get("username") != null ? map.get("username") : "")
                .when()
                .get("/order-report/meta-data/order-types")  
                .then() 
                .extract().response();    
         
                if (response.statusCode() == 200) {
					System.out.println("Description: Success");
    
              if (response.jsonPath().get("_metadata") != null) {    
              if (response.jsonPath().get("_metadata.hasNext") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("_metadata.hasNext"), instanceOf(Boolean.class));  
          }
    
              if (response.jsonPath().get("_metadata.count") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("_metadata.count"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("_metadata.totalCount") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("_metadata.totalCount"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("_metadata.requestId") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("_metadata.requestId"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("_metadata.channel") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("_metadata.channel"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("_metadata.totalFailedOrderCount") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("_metadata.totalFailedOrderCount"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("_metadata.totalCompletedOrderCount") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("_metadata.totalCompletedOrderCount"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("_metadata.totalPendingOrderCount") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("_metadata.totalPendingOrderCount"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("_metadata.totalInProgressOrderCount") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("_metadata.totalInProgressOrderCount"), instanceOf(String.class));  
          }
  
          }
    
              if (response.jsonPath().get("results") != null) {    
                for (int i = 0; i < response.jsonPath().getList("results").size(); i++) {    
              if (response.jsonPath().get("results["+ i +"].orderType") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("results["+ i +"].orderType"), instanceOf(String.class));  
          }
    
                  }  
                MatcherAssert.assertThat(response.jsonPath().getList("results"), instanceOf(List.class));
  
          }
				}
if (response.statusCode() == 400) {
					System.out.println("Description: Bad Request");
    
              if (response.jsonPath().get("code") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("code"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("message") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("message"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("status") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("status"), instanceOf(String.class));  
          }
				}
if (response.statusCode() == 401) {
					System.out.println("Description: Unauthorized");
    
              if (response.jsonPath().get("code") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("code"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("message") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("message"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("status") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("status"), instanceOf(String.class));  
          }
				}
if (response.statusCode() == 403) {
					System.out.println("Description: Forbidden");
    
              if (response.jsonPath().get("code") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("code"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("message") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("message"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("status") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("status"), instanceOf(String.class));  
          }
				}
if (response.statusCode() == 404) {
					System.out.println("Description: Not Found");
    
              if (response.jsonPath().get("code") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("code"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("message") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("message"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("status") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("status"), instanceOf(String.class));  
          }
				}
if (response.statusCode() == 405) {
					System.out.println("Description: Method Not allowed");
    
              if (response.jsonPath().get("code") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("code"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("message") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("message"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("status") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("status"), instanceOf(String.class));  
          }
				}
if (response.statusCode() == 409) {
					System.out.println("Description: Conflict");
    
              if (response.jsonPath().get("code") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("code"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("message") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("message"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("status") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("status"), instanceOf(String.class));  
          }
				}
if (response.statusCode() == 500) {
					System.out.println("Description: Internal Server Error");
    
              if (response.jsonPath().get("code") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("code"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("message") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("message"), instanceOf(String.class));  
          }
    
              if (response.jsonPath().get("status") != null) {
                MatcherAssert.assertThat(response.jsonPath().get("status"), instanceOf(String.class));  
          }
				}
  
            }  
        } catch (IOException e) {  
            e.printStackTrace();  
        }  
    }
}
