
// ********RoostGPT********
/*
Test generated by RoostGPT for test test-roostapispec-1 using AI Type Claude AI and AI Model claude-3-5-sonnet-20240620

Test generated for /test_post for http method type POST in rest-assured framework

RoostTestHash=83193a8b39



roost_feedback [8/13/2024, 2:30:34 AM]:sas
*/

// ********RoostGPT********

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;

public class TestPostEndpoint {

    @BeforeAll
    public static void setup() {
        RestAssured.baseURI = "https://api.example.com";
    }

    @Test
    public void testPostEndpoint() {
        String requestBody = "{\"key\": \"value\"}";

        Response response = given()
            .contentType(ContentType.JSON)
            .body(requestBody)
        .when()
            .post("/test_post")
        .then()
            .statusCode(200)
            .contentType(ContentType.JSON)
            .body("message", equalTo("Success"))
            .body("data", notNullValue())
            .extract().response();

        // Additional assertions
        String responseBody = response.getBody().asString();
        assertThat(responseBody, containsString("Success"));
        assertThat(response.getTime(), lessThan(5000L));
    }
}
