// Test generated by RoostGPT for test Koreai-restassured using AI Type Open AI and AI Model gpt-4-1106-preview

// Test generated for /TransferFunds_post for http method type POST in rest-assured framework

// RoostTestHash=289ed66c26

package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

public class TransferFundsPostTest {

    @Test
    public void transferFundsPostTest() {
        RestAssured.baseURI = System.getenv("BASE_URL");

        // Read CSV file
        try (BufferedReader reader = new BufferedReader(new FileReader("src/test/java/com/bootexample4/RoostTest/TransferFunds_post.csv"))) {
            String headerLine = reader.readLine();
            String[] headers = headerLine.split(",");

            String line;
            while ((line = reader.readLine()) != null) {
                String[] data = line.split(",");

                // Create a map of header to data
                Map<String, String> requestData = new HashMap<>();
                for (int i = 0; i < headers.length; i++) {
                    requestData.put(headers[i], data[i]);
                }

                Response response = given()
                        .pathParams(
                                "koreUserId", requestData.get("koreUserId"),
                                "botId", requestData.get("botId"),
                                "userCode", requestData.get("userCode"),
                                "accountId", requestData.get("accountId"))
                        .header("Authorization", requestData.get("Authorization"))
                        .contentType(ContentType.JSON)
                        .body(requestData)
                        .when()
                        .post("/TransferFunds")
                        .then()
                        .contentType(ContentType.JSON)
                        .extract().response();

                // Handle different status codes
                switch (response.statusCode()) {
                    case 200:
                        validateSuccessResponse(response);
                        break;
                    case 400:
                        validateErrorResponse(response);
                        break;
                    case 401:
                        validateUnauthorisedResponse(response);
                        break;
                    case 404:
                        validateNotFoundResponse(response);
                        break;
                    case 422:
                        validateUnprocessableEntityResponse(response);
                        break;
                    default:
                        throw new IllegalStateException("Unexpected response status: " + response.statusCode());
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void validateSuccessResponse(Response response) {
        response.then().statusCode(200)
                .body("transactionId", notNullValue())
                .body("status", equalTo("SUCCESS"));
    }

    private void validateErrorResponse(Response response) {
        response.then().statusCode(400)
                .body("err", notNullValue())
                .body("err.message", instanceOf(String.class));
    }

    private void validateUnauthorisedResponse(Response response) {
        response.then().statusCode(401)
                .body("err", notNullValue())
                .body("err.message", equalTo("Error: Authorization failed."));
    }

    private void validateNotFoundResponse(Response response) {
        response.then().statusCode(404)
                .body("err", notNullValue())
                .body("err.message", equalTo("Error: Not Found"));
    }

    private void validateUnprocessableEntityResponse(Response response) {
        response.then().statusCode(422)
                .body("err", notNullValue())
                .body("err.message", instanceOf(String.class))
                .body("err.details", notNullValue());
    }
}
