# ********RoostGPT********

# Test generated by RoostGPT for test testing-karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /context/{context-id}/environment-variable_get for http method type GET 
# RoostTestHash=557b8b225f
# 
# 

# ********RoostGPT********
Feature: List Environment Variables

  Background:
    * def baseURL = karate.properties['CIRCLECI_API_BASE_URL'] || karate.properties['CIRCLECI_API_BASE_URL']
    * url baseURL
    * configure report = false
    * def username = karate.properties['API_AUTH_USERNAME']
    * def password = karate.properties['API2_AUTH_PASSWORD']
    * def credentials = username + ':' + password
    * def encoded = Java.type('java.util.Base64').getEncoder().encodeToString(credentials.getBytes())
    * def authHeader = 'Basic ' + encoded
    * configure headers = { Authorization: '#(authHeader)' , Accept: 'application/json' }

  Scenario Outline: Verify listing environment variables with valid inputs
    Given path 'context', '<context_id>', 'environment-variable'
    And param page-token = <page_token>
    When method GET
    Then status 200
    And match response.items == '#[]'
    And match each response.items[*].variable == '#string'
    And match each response.items[*].created_at == '#string'
    And match each response.items[*].created_at == '#regex (20|19)[0-9]{2}-[0-1][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]{3}Z'
    And match each response.items[*].updated_at == '#string'
    And match each response.items[*].updated_at == '#regex (20|19)[0-9]{2}-[0-1][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]{3}Z'
    And match each response.items[*].context_id == '#string'
    And match each response.items[*].context_id == '#uuid'
    And match response.next_page_token == '#? _ == null || typeof _ == "string"'

    Examples:
      | read('context_context-id_environment-variable_get.csv') |

  Scenario: Verify error response for missing context-id
    Given path 'context', '', 'environment-variable'
    When method GET
    Then status != 200
    And match response.message == '#string'

  Scenario Outline: Verify error response for invalid inputs
    Given path 'context', '<context_id>', 'environment-variable'
    And param page-token = <page_token>
    When method GET
    Then status != 200
    And match response.message == '#string'

    Examples:
      | context_id                             | page_token           |
      | 'invalid-id-123'                       | 'invalid'            |
      | '8fbd3e1c-5a17-44d4-abc3-9876543210ef' | 'INVALID_PAGE_TOKEN' |

  Scenario: Verify headers in the success response
    Given path 'context', '026a0b5d-9e0b-4f84-9a3b-123456abcd89', 'environment-variable'
    When method GET
    Then status 200
    And match responseHeaders['Content-Type'] == 'application/json'
