# ********RoostGPT********

# Test generated by RoostGPT for test new-circle-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /context/{context-id}_get for http method type GET 
# RoostTestHash=d311758cf3
# 
# 

# ********RoostGPT********
Feature: API Tests for Get Context Endpoint

  Background:
    * def baseURL = karate.properties['CIRCLECI_API_BASE_URL'] || karate.properties['API_HOST']
    * def authToken = karate.properties['circle-token']
    * url baseURL
    * header Accept = 'application/json'

  Scenario Outline: Verify Get Context API functionality for valid context ID
    Given path 'context/<context_id>'
    And param circle-token = authToken
    When method GET
    Then status 200
    And match response == '#object'
    And match response.id == '#uuid'
    And match response.name == '#string'
    And match response.created_at == "#regex ^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z"

    Examples:
      | read('context_context-id_get.csv') |

  Scenario Outline: Validate error response for invalid context ID
    Given path 'context/<context_id>'
    And param circle-token = authToken
    When method GET
    Then status 401
    And match response == '#object'
    And match response.message == '#string'

    Examples:
      | context_id             |
      | ['invalid-context-id'] |

  Scenario: Verify response headers for valid request
    Given path 'context/c5d8e4e2-8f5d-4bcc-aeb2-d18e3b4a0009'
    And param circle-token = authToken
    When method GET
    Then status 200
    And match responseHeaders['Content-Type'] == '#string'
