# ********RoostGPT********

# Test generated by RoostGPT for test testing-karate1 using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /employees/{id}_get for http method type GET 
# RoostTestHash=36bc161fb6
# 
# 

# ********RoostGPT********
Feature: Employee Management

    Background:
        * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
        * url urlBase

    Scenario Outline: Validate GET /employees/{id} endpoint
        Given path 'employees', <id>
        And header Authorization = karate.properties['AUTH_TOKEN']
        When method get
        Then status <status_code>
        And match response contains {id:'#(id)', jobTitle:'#string', name:'#string', email:'#string'}

        Examples:
            | id                                     | status_code |
            | 'd290f1ee-6c54-4b01-90e6-d701748f0851' | 200         |
            | 'd290f1ee-6c54-4b01-90e6-d701748f0852' | 404         |
