# ********RoostGPT********

# Test generated by RoostGPT for test testing-karate1 using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /employees_get for http method type GET 
# RoostTestHash=ec231a756b
# 
# 

# ********RoostGPT********
Feature: Employees API

    Background:
        * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
        * url urlBase
        * def authToken = karate.properties['AUTH_TOKEN']
        * header Authorization = authToken

    Scenario Outline: Search Employees
        Given path '/employees'
        And param searchString = '<searchString>'
        When method get
        Then status 200
        And match response contains { email:'#string', jobTitle:'#string', name:'#string' }
        And match each response[*].email contains '#string'
        And match each response[*].jobTitle contains '#string'
        And match each response[*].name contains '#string'

        Examples:
            | searchString |
            | 'John'       |
            | 'Analyst'    |
            | 'acme'       |

    Scenario Outline: Search Employees with Invalid Input
        Given path '/employees'
        And param searchString = '<searchString>'
        When method get
        Then status 400

        Examples:
            | searchString |
            | '12345'      |
            | ''           |
