# ********RoostGPT********

# Test generated by RoostGPT for test testing-finnhub-integratiopn using AI Type Open AI and AI Model gpt-4
# 
# ROOST_METHOD_HASH=58eeb24062
# ROOST_METHOD_SIG_HASH=d5c655d95c
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Retrieve Peer Stocks and their Time Series Data',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Get peers for a given stock symbol and their time series values',
#     steps: "Given an API key '<FINNHUB_API_KEY>' for Finnhub \n" +
#       "And an API key '<ALPHAVANTAGE_API_KEY>' for AlphaVantage\n" +
#       "And a stock symbol 'AAPL'\n" +
#       "When I retrieve the peer stock symbols from 'https://finnhub.io/api/v1/stock/peers' with the API key\n" +
#       'Then I should get a list of peer stock symbols\n' +
#       "When I retrieve the time series values for each peer stock symbol from 'https://www.alphavantage.co/query' with the API key\n" +
#       'Then I should get the time series data for each peer stock symbol',
#     examples: 'Examples:\n' +
#       '    | FINNHUB_API_KEY     | ALPHAVANTAGE_API_KEY      |\n' +
#       '    | your_finnhub_api_key | your_alphavantage_api_key |'
#   }
# }
# 

# ********RoostGPT********
Feature: Retrieve Peer Stocks and their Time Series Data

  Background:
    * def ALPHAVANTAGE_GET_RESOLVED_8BEF8E59C6_URL = karate.properties['ALPHAVANTAGE_GET_RESOLVED_8BEF8E59C6_URL'] || karate.get('ALPHAVANTAGE_GET_RESOLVED_8BEF8E59C6_URL', 'http://localhost:4010')
    * def FINNHUB_E706FCCD58_URL = karate.properties['FINNHUB_E706FCCD58_URL'] || karate.get('FINNHUB_E706FCCD58_URL', 'http://localhost:4010')
    * def ALPHAVANTAGE_GET_RESOLVED_8BEF8E59C6_AUTH_TOKEN = karate.properties['ALPHAVANTAGE_GET_RESOLVED_8BEF8E59C6_AUTH_TOKEN'] || karate.get('ALPHAVANTAGE_GET_RESOLVED_8BEF8E59C6_AUTH_TOKEN', 'Bearer_Dummy_Token')
    * def FINNHUB_E706FCCD58_AUTH_TOKEN = karate.properties['FINNHUB_E706FCCD58_AUTH_TOKEN'] || karate.get('FINNHUB_E706FCCD58_AUTH_TOKEN', 'Bearer_Dummy_Token')

  Scenario Outline: Get peers for a given stock symbol and their time series values
    Given def FINNHUB_API_KEY = '<FINNHUB_API_KEY>'
    And def ALPHAVANTAGE_API_KEY = '<ALPHAVANTAGE_API_KEY>'
    And def symbol = 'AAPL'
    # Retrieve the peer stock symbols
    * url FINNHUB_E706FCCD58_URL
    And path '/stock/peers'
    And param symbol = symbol
    And param token = FINNHUB_API_KEY
    When method get
    Then status 200
    And def peerSymbols = response
    # Retrieve the time series values for each peer stock symbol
    * url ALPHAVANTAGE_GET_RESOLVED_8BEF8E59C6_URL
    And path '/query'
    And param function = 'TIME_SERIES_DAILY'
    And param symbol = '#(peerSymbols)'
    And param apikey = ALPHAVANTAGE_API_KEY
    When method get
    Then status 200

    Examples:
      | FINNHUB_API_KEY      | ALPHAVANTAGE_API_KEY      |
      | your_finnhub_api_key | your_alphavantage_api_key |
