# ********RoostGPT********

# Test generated by RoostGPT for test testing-karate using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /pet/findByTags_get for http method type GET 
# RoostTestHash=5d35dc4296
# 
# 

# ********RoostGPT********
Feature: Test /pet/findByTags endpoint

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * configure headers = {Authorization: '#(karate.properties['AUTH_TOKEN'])'}

Scenario: Find pets by valid tags
  Given path '/pet/findByTags'
  And param tags = 'tag1,tag2,tag3'
  When method GET
  Then status 200
  And match response == '#[_ > 0]'
  And match each response contains
    """
    {
      id: '#number',
      name: '#string',
      photoUrls: '#array',
      category: {
        id: '#number',
        name: '#string'
      },
      tags: '#array',
      status: '#string'
    }
    """
  And match each response.tags contains {id: '#number', name: '#string'}
  And match each response.photoUrls == '#array'
  And match each response.status == '#string'

Scenario: Find pets by invalid tag value
  Given path '/pet/findByTags'
  And param tags = 'invalidTag'
  When method GET
  Then status 400
  And match response == '"Invalid tag value"'

Scenario: Find pets without tags parameter
  Given path '/pet/findByTags'
  When method GET
  Then status 200
  And match response == '#[_ == 0]'
