# ********RoostGPT********

# Test generated by RoostGPT for test karate_open_testing using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /GetAccountInfo_post for http method type POST 
# RoostTestHash=8a95fbc531
# 
# 

# ********RoostGPT********
Feature: GetAccountInfo API Tests

  Background:
    * def urlBase = karate.properties['PETSTORE_API_HOST']
    * url urlBase

  Scenario Outline: Get account information successfully with valid payload and headers
    Given path 'GetAccountInfo'
    And header Authorization = <Authorization>
    And header botId = <botId>
    And header accountId = <accountId>
    And header X-CORRELATION-ID = <X_CORRELATION_ID>
    And header X-Auth-token = <X_Auth_token>
    And request """ 
      { 
        "customerId": <customerId> 
      } 
    """
    When method POST
    Then status 200
    And match response.customerId == '#number'
    And match response.accounts == '#[]'
    And match response.accounts[*].customerId == '#number'
    And match response.accounts[*].accountName == '#string'
    And match response.accounts[*].accountNickname == '#string'
    And match response.accounts[*].accountNumber == '#string'
    And match response.accounts[*].accountType == '#string'
    And match response.accounts[*].activatedDate == '#string'
    And match response.accounts[*].availableBalance == '#number'
    And match response.accounts[*].availableCash == '#number'
    And match response.accounts[*].availableCashLimit == '#number'
    And match response.accounts[*].availableCredit == '#number'
    And match response.accounts[*].bankName == '#string'
    And match response.accounts[*].branchName == '#string'
    And match response.accounts[*].cardName == '#string'
    And match response.accounts[*].cardNumber == '#string'
    And match response.accounts[*].cardStatus == '#string'
    And match response.accounts[*].cardType == '#string'
    And match response.accounts[*].creditLimit == '#number'
    And match response.accounts[*].currency == '#string'
    And match response.accounts[*].currentBalance == '#number'
    And match response.accounts[*].deactivatedDate == '#string'
    And match response.accounts[*].dueAmount == '#number'
    And match response.accounts[*].dueDate == '#string'
    And match response.accounts[*].earlyWithdrawalPenalty == '#number'
    And match response.accounts[*].email == '#string'
    And match response.accounts[*].expiryDate == '#string'
    And match response.accounts[*].expDate == '#string'
    And match response.accounts[*].fdType == '#string'
    And match response.accounts[*].image == '#string'
    And match response.accounts[*].interestRate == '#number'
    And match response.accounts[*].internalTransferFromEnabled == '#boolean'
    And match response.accounts[*].internalTransferToEnabled == '#boolean'
    And match response.accounts[*].isPrimaryMobile == '#boolean'
    And match response.accounts[*].isAlternateMobileNumber == '#boolean'
    And match response.accounts[*].isStatement == '#boolean'
    And match response.accounts[*].lastDrawDate == '#string'
    And match response.accounts[*].loanMaturityDate == '#string'
    And match response.accounts[*].loanOriginationDate == '#string'
    And match response.accounts[*].location == '#string'
    And match response.accounts[*].lastUpdated == '#string'
    And match response.accounts[*].maxTransactionLimit == '#string'
    And match response.accounts[*].maturityDate == '#string'
    And match response.accounts[*].minimumPaymentDue == '#string'
    And match response.accounts[*].minimumBalance == '#string'
    And match response.accounts[*].monthlyPayment == '#number'
    And match response.accounts[*].openingBalance == '#number'
    And match response.accounts[*].originalLoanAmount == '#number'
    And match response.accounts[*].P2PLimit == '#number'
    And match response.accounts[*].p2pEnabled == '#number'
    And match response.accounts[*].paybillEnabled == '#boolean'
    And match response.accounts[*].payoffAmount == '#number'
    And match response.accounts[*].personalBankerName == '#string'
    And match response.accounts[*].personalBankerContact.email == '#string'
    And match response.accounts[*].personalBankerContact.mobileNumber == '#string'
    And match response.accounts[*].phone == '#number'
    And match response.accounts[*].postedBalance == '#number'
    And match response.accounts[*].principalBalance == '#string'
    And match response.accounts[*].productCode == '#string'
    And match response.accounts[*].productName == '#string'
    And match response.accounts[*].propertyAddress == '#string'
    And match response.accounts[*].rewardPoints == '#string'
    And match response.accounts[*].routingNumber == '#string'
    And match response.accounts[*].statementDate == '#string'
    And match response.accounts[*].status == '#string'
    And match response.accounts[*].swiftCode == '#string'
    And match response.accounts[*].totalBalance == '#number'
    And match response.accounts[*].unbilledAmount == '#number'
    And match response.accounts[*].userId == '#string'
    And match response.accounts[*].valueAtMaturity == '#number'
    And match response.accounts[*].holdAmount == '#number'
    And match response.accounts[*].unclearFundsAmount == '#number'
    And match response.accounts[*].averageMonthlyBalance == '#number'
    And match response.accounts[*].netWithdrawableBalance == '#number'
    And match response.accounts[*].totalTenure == '#string'
    And match response.accounts[*].remainingTenure == '#string'
    And match response.accounts[*].debitAccountNumber == '#string'
    And match response.accounts[*].lateFee == '#number'
    And match response.accounts[*].bounceCharge == '#number'
    And match response.accounts[*].totalCharges == '#number'
    And match response.accounts[*].overDueAmount == '#number'
    And match response.accounts[*].id == '#string'

    Examples:
      | Authorization | botId    | accountId | X_CORRELATION_ID | X_Auth_token | customerId |
      | 'Bearer xyz'  | 'Bot123' | 'Acc456'  |            10001 | 'Token456'   |    1045300 |

  Scenario Outline: Authorization failed
    Given path 'GetAccountInfo'
    And header Authorization = <Authorization>
    And header botId = <botId>
    And header accountId = <accountId>
    And header X-CORRELATION-ID = <X_CORRELATION_ID>
    And request """ 
      { 
        "customerId": <customerId> 
      } 
    """
    When method POST
    Then status 401
    And match response.err.message == '#string'

    Examples:
      | Authorization | botId    | accountId | X_CORRELATION_ID | customerId |
      | ''            | 'Bot123' | 'Acc456'  |            10001 |    1045300 |

  Scenario Outline: Resource not found
    Given path 'GetAccountInfo'
    And header Authorization = <Authorization>
    And header botId = <botId>
    And header accountId = <accountId>
    And header X-CORRELATION-ID = <X_CORRELATION_ID>
    And header X-Auth-token = <X_Auth_token>
    And request """ 
      { 
        "customerId": <customerId> 
      } 
    """
    When method POST
    Then status 404
    And match response.err.message == '#string'

    Examples:
      | Authorization | botId    | accountId | X_CORRELATION_ID | X_Auth_token | customerId |
      | 'Bearer xyz'  | 'Bot999' | 'Acc999'  |            10001 | 'Token999'   |          0 |
