# ********RoostGPT********

# Test generated by RoostGPT for test karate_open_testing using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /GetAccountInfo_post for http method type POST 
# RoostTestHash=8a95fbc531
# 
# 

# ********RoostGPT********
Feature: GetAccountInfo - Fetch customer account details

Background:
    * def urlBase = karate.properties['PETSTORE_API_HOST']
    * url urlBase

Scenario Outline: Validate GET /GetAccountInfo endpoint

    Given path 'GetAccountInfo'
    And header Authorization = '#(authorization)'
    And header botId = '<botId>'
    And header accountId = '<accountId>'
    And header koreUserId = '<koreUserId>'
    And header X-Auth-token = '<xAuthToken>'
    And header X-CORRELATION-ID = <xCorrelationId>
    And request 
      """
      {
        "customerId": <customerId>
      }
      """
    When method GET
    Then match responseStatus == <expectedHttpStatus>
    And match response == <expectedResponseSchema>
    And assert karate.sizeOf(response) >= <minimumKeysInResponse>

Examples:
    | authorization      | botId    | accountId   | koreUserId | xAuthToken | xCorrelationId | customerId | expectedHttpStatus | expectedResponseSchema | minimumKeysInResponse |
    | 'Bearer xyz_token' | 'bot123' | 'acc001'    | 'user123'  | 'token123' | 101010          | 1045300    | 200                | {
        "customerId": 1045300,
        "accounts": [
          {
            "customerId": 1045300,
            "accountName": "#string",
            "accountNickname": "#string",
            "accountNumber": "#string",
            "accountType": "#string",
            "activatedDate": "#string",
            "availableBalance": "#number",
            "currency": "#string",
            "dueDate": "#? _ == null || typeof _ == 'string'",
            "expiryDate": "#? _ == null || typeof _ == 'string'"
          }
        ]
      }                          | 3              |
    | 'Bearer another_token'     | 'bot456' | 'acc002' | 'user001' | 'token456' | 202020 | 1045305 | 401 | { "err": { "message": "#string" } } | 1 |
    | 'Bearer dummyToken' | 'botXYZ' | 'acc_null'    | 'user789'  | null        | 303030          | 1045310    | 404                | { "err": { "message": "#string" } } | 1  |

Scenario: Validate GET /GetAccountInfo endpoint responses for 401 and 404 status codes

    Given path 'GetAccountInfo'
    And header Authorization = '#(authorization)'
    And header botId = 'botXYZ'
    And header accountId = 'invalidAccount'
    And header koreUserId = 'koreUserInvalid'
    And header X-Auth-token = null
    And header X-CORRELATION-ID = 404404
    And request 
      """
      {
        "customerId": 999999
      }
      """
    When method GET
    Then assert responseStatus != 200
    And match response.err.message == '#string'
