# ********RoostGPT********

# Test generated by RoostGPT for test karate_open_testing using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /GetTransactions_post for http method type POST 
# RoostTestHash=207beafabe
# 
# 

# ********RoostGPT********
Feature: GetTransactions API Test Suite

  Background:
    * def urlBase = karate.properties['PETSTORE_API_HOST']
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Verify GetTransactions with valid payload
    Given path 'GetTransactions'
    And headers { 'botId': '<botId>', 'accountId': '<accountId>', 'Authorization': '<Authorization>', 'koreUserId': '<koreUserId>', 'X-Auth-token': '<X_Auth_token>', 'X-CORRELATION-ID': <X_CORRELATION_ID> }
    And request
      """
      {
        "customerId": <customerId>,
        "accountNumber": <accountNumber>,
        "category": <category>,
        "startDate": "<startDate>",
        "endDate": "<endDate>",
        "status": "<status>",
        "transactionAmount": <transactionAmount>
      }
      """
    When method POST
    Then status 200
    And match response == '#[]'
    And match each response[*].customerId == '##number'
    And match each response[*].transactionId == '##number'
    And match each response[*].accountNumber == '#string'
    And match each response[*].timestamp == '##number'
    And match each response[*].amount == '##number'
    And match each response[*].currency == '#string'
    And match each response[*].debitOrCredit == '#string'
    And match each response[*].description == '#string'
    And match each response[*].paymentMode == '##string'
    And match each response[*].DBANames == '##string'
    And match each response[*].status == '#string'
    And match each response[*].closingBalance == '##number'
    And match each response[*].transacitonType == '#string'
    And match each response[*].ACHCode == '##string'
    And match each response[*].MCCCode == '##string'
    And match each response[*].SICCode == '##string'
    And match each response[*].name == '##string'
    And match each response[*].address == '##string'
    And match each response[*].street == '##string'
    And match each response[*].city == '##string'
    And match each response[*].state == '##string'
    And match each response[*].zip == '##string'
    And match each response[*].country == '##string'
    And match each response[*].phoneNumber == '##number'
    And match each response[*].metaInfo == '#[]'
    And match each response[*].metaInfo[*].name == '#string'
    And match each response[*].metaInfo[*].value == '#string'

    Examples:
      | read('GetTransactions_post.csv') |
