# ********RoostGPT********

# Test generated by RoostGPT for test karate_open_testing using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /GetTransactions_post for http method type POST 
# RoostTestHash=207beafabe
# 
# 

# ********RoostGPT********
Feature: GetTransactions API

  Background:
    * def urlBase = karate.properties['PETSTORE_API_HOST']
    * url urlBase

  Scenario Outline: Validate GET /GetTransactions endpoint response with various headers and body parameters
    Given path 'GetTransactions'
    And headers """ 
    { 
      "Authorization": "<Authorization>", 
      "botId": "<botId>", 
      "accountId": "<accountId>", 
      "koreUserId": "<koreUserId>", 
      "X-Auth-token": "<X_Auth_token>", 
      "X-CORRELATION-ID": "<X_CORRELATION_ID>" 
    } 
    """
    And request """
    { 
      "customerId": "<customerId>",
      "accountNumber": "<accountNumber>", 
      "startDate": "<startDate>", 
      "endDate": "<endDate>", 
      "numOfTransactions": <numOfTransactions>, 
      "status": "<status>", 
      "sort": { "type": "<sortType>", "value": "<sortValue>" }, 
      "transactionAmount": { "amount1": <amount1>, "amount": <amount>, "currency": "<currency>" },
      "category": [ 
        { 
          "codeType": "<codeType>", 
          "value": <value>, 
          "source": "<source>" 
        } 
      ],
      "debitOrCredit": "<debitOrCredit>"
    }
    """
    When method post
    Then status 200
    And match response == '#[]'
    And match response[0].customerId == '#number'
    And match response[0].transactionId == '#number'
    And match response[0].accountNumber == '#string'
    And match response[0].timestamp == '#number'
    And match response[0].amount == '#number'
    And match response[0].currency == '#string'
    And match response[0].debitOrCredit == '#string'
    And match response[0].description == '#string'
    And match response[0].paymentMode == '#string'
    And match response[0].DBANames == '#string'
    And match response[0].status == '#string'
    And match response[0].transactionType == '#string?'
    And match response[0].MCCCode == '#number?'
    And match response[0].name == '#string'
    And match response[0].address == '#string'
    And match response[0].street == '#string'
    And match response[0].city == '#string'
    And match response[0].state == '#string'
    And match response[0].zip == '#string'
    And match response[0].country == '#string'
    And match response[0].phoneNumber == '#number?'

    Examples:
      | Authorization | botId | accountId | koreUserId | X_Auth_token   | X_CORRELATION_ID | customerId | accountNumber       | startDate                         | endDate                           | numOfTransactions | status  | sortType | sortValue | amount1 | amount       | currency | codeType | value                 | source    | debitOrCredit |
      | token123      | 10101 | 20202     | userId123  | authToken123   | 12345            | 1045300    | 1045301             | 2021-04-01T00:00:00.000+0000      | 2021-04-30T00:00:00.000+0000      | 10               | Posted  | amount   | gt        | 2000    | 1000         | USD      | MCC     | 5811,5814            | Internal  | Credit        |
