# ********RoostGPT********

# Test generated by RoostGPT for test testing-karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /employees_get for http method type GET 
# RoostTestHash=ec231a756b
# 
# 

# ********RoostGPT********
Feature: Employee Search

Background:
  * def authToken = karate.properties['AUTH_TOKEN']
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def headers = { Authorization: '#(authToken)' }
  * configure headers = headers

Scenario Outline: Search for employees with optional search string

  Given path '/employees'
  And param searchString = '<searchString>'
  When method get
  Then status 200
  And match response contains {jobTitle: '#string', name: '#string', email: '#string'}
  And match each response[*].id == '#uuid'
  And match each response[*].jobTitle == '#string'
  And match each response[*].name == '#string'
  And match each response[*].email == '#string'

Examples:
  | searchString |
  | 'John'       |
  | 'Analyst'    |

Scenario: Search for employees with invalid request

  Given path '/employees'
  And param searchString = 12345
  When method get
  Then status 400
