# ********RoostGPT********

# Test generated by RoostGPT for test testing-karate using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /pet/findByTags_get for http method type GET 
# RoostTestHash=5d35dc4296
# 
# 

# ********RoostGPT********
Feature: Find Pets by Tags

Background:
* def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
* url urlBase
* configure headers = { 'Content-Type': 'application/json', 'api_key': #(karate.properties['AUTH_TOKEN'] || '{{$processEnvironment.AUTH_TOKEN}}') }

Scenario Outline: Find Pets by Tags - <status>
    Given path '/pet/findByTags'
    And param tags = <tags>
    When method GET
    Then status 200
    And match each response contains 
    """
    {
        id: '#number',
        name: '#string',
        category: {
            id: '#number',
            name: '#string'  
        },
        photoUrls: '#array',
        tags: '#array',
        status: '#string'
    }
    """
    And match each response.status == <status>

    Examples:
      | tags              | status     |
      | ['tag1']          | 'available'| 
      | ['tag2', 'tag3']  | 'pending'  |
      | ['tag1', 'tag2']  | 'sold'     |

Scenario: Find Pets by Tags - Invalid tag value
    Given path '/pet/findByTags'
    And param tags = 'invalid'
    When method GET
    Then status 400
